import type { Bottle, Review } from "@prisma/client";

export const bottle1: Bottle = {
  id: "07395219-195d-4050-b68f-2baef911c2de",
  name: "Elijah Craig Barrel Proof",
  type: "Bourbon",
  distiller: "Heaven Hill",
  bottler: "Elijah Craig",
  producer: "Elijah Craig",
  country: "USA",
  region: "Kentucky",
  price: "69.99",
  age: "12yrs",
  year: "2022",
  batch: "A122",
  alcoholPercent: "60.4%",
  proof: "120.8pf",
  size: "750ml",
  color: "Amber",
  finishing: "None",
};

export const bottle2: Bottle = {
  id: "89294c69-e9f6-4df4-9b93-a01f8e88523a",
  name: "Four Roses SiB BS OBSV",
  type: "Bourbon",
  distiller: "Four Roses",
  bottler: "Four Roses",
  producer: "Four Roses",
  country: "USA",
  region: "Kentucky",
  price: "140",
  age: "9yrs 5mos",
  year: "2022",
  batch: "Binny's Pick",
  alcoholPercent: "56.3",
  proof: "112.6",
  size: "750ml",
  color: "Brick",
  finishing: "None",
};

export const bottle3: Bottle = {
  id: "8e6e7281-ca57-4e1e-84de-9a50f3bbeb09",
  name: "Kirkland Single Barrel",
  type: "Bourbon",
  distiller: "Barton 1792",
  bottler: "Barton 1792",
  producer: "Barton 1792",
  country: "USA",
  region: "Kentucky",
  price: "34.99",
  age: "NAS",
  year: "2022",
  batch: "N/A",
  alcoholPercent: "60",
  proof: "120",
  size: "1L",
  color: "Straw",
  finishing: "None",
};

export const review1: Omit<
  Review,
  "bottleId" | "createdAt" | "updatedAt" | "userId"
> = {
  id: "dbac11ca-2b24-4530-bd86-b3d047823180",
  imageUrl: "fe8767e3-a311-45a6-a9db-cfe581e7e2b3",

  date: "01/01/2023",
  setting: "Having some bourbon after a day of work",
  glassware: "Copita",
  restTime: "10min",
  nose: "Nutty as all hell, toffee, caramel, cinnamon, burnt sugar, sweet oak, old rickhouse, black pepper, clove, confectioner sugar, grape, plum, almost smells finished.",
  palate:
    "Black peppercorns, cinnamon, caramel, salty tortilla chips, fudge, pecans, confectioners sugar, light clove.",
  finish:
    "Strong, sweet oak, black peppercorn, big caramel notes round the palate. Mint, chocolate, there's a really light fruit note that I can't quite place, but it's well balanced with the darker flavors of the finish.",
  thoughts:
    "Really good stuff. Dark flavors dominate with the caramel, dark chocolate, and peppercorns. There's small waves of a light fruit note I still can't quite place, maybe green grapes? It's really well balanced with the caramel, oak, and chocolate, plus the baking spices and mint make the finish last for a long, long time.",
  cherry: 6,
  strawberry: 6,
  raspberry: 6,
  blackberry: 6,
  blueberry: 6,
  apple: 6,
  banana: 6,
  grape: 6,
  stone: 6,
  citrus: 6,
  tropical: 6,
  pepper: 6,
  bakingSpice: 6,
  cinnamon: 6,
  herbal: 6,
  mint: 6,
  coffee: 6,
  tobacco: 6,
  leather: 6,
  oak: 6,
  toasted: 6,
  smokey: 6,
  peanut: 6,
  almond: 6,
  pecan: 6,
  walnut: 6,
  oily: 6,
  floral: 6,
  corn: 6,
  rye: 6,
  wheat: 6,
  malt: 6,
  dough: 6,
  vanilla: 6,
  caramel: 6,
  molasses: 6,
  butterscotch: 6,
  honey: 6,
  chocolate: 6,
  toffee: 6,
  sugar: 6,
  overallRating: 6,
  value: 6,
};

export const review2: Omit<
  Review,
  "bottleId" | "createdAt" | "updatedAt" | "userId"
> = {
  id: "130ef50a-48e9-4067-af29-880fa630733a",
  imageUrl: "fe8767e3-a311-45a6-a9db-cfe581e7e2b3",

  date: "01/01/2023",
  setting: "Having some bourbon after a day of work",
  glassware: "Copita",
  restTime: "10min",
  nose: "Nutty as all hell, toffee, caramel, cinnamon, burnt sugar, sweet oak, old rickhouse, black pepper, clove, confectioner sugar, grape, plum, almost smells finished.",
  palate:
    "Black peppercorns, cinnamon, caramel, salty tortilla chips, fudge, pecans, confectioners sugar, light clove.",
  finish:
    "Strong, sweet oak, black peppercorn, big caramel notes round the palate. Mint, chocolate, there's a really light fruit note that I can't quite place, but it's well balanced with the darker flavors of the finish.",
  thoughts:
    "Really good stuff. Dark flavors dominate with the caramel, dark chocolate, and peppercorns. There's small waves of a light fruit note I still can't quite place, maybe green grapes? It's really well balanced with the caramel, oak, and chocolate, plus the baking spices and mint make the finish last for a long, long time.",
  cherry: 6,
  strawberry: 6,
  raspberry: 6,
  blackberry: 6,
  blueberry: 6,
  apple: 6,
  banana: 6,
  grape: 6,
  stone: 6,
  citrus: 6,
  tropical: 6,
  pepper: 6,
  bakingSpice: 6,
  cinnamon: 6,
  herbal: 6,
  mint: 6,
  coffee: 6,
  tobacco: 6,
  leather: 6,
  oak: 6,
  toasted: 6,
  smokey: 6,
  peanut: 6,
  almond: 6,
  pecan: 6,
  walnut: 6,
  oily: 6,
  floral: 6,
  corn: 6,
  rye: 6,
  wheat: 6,
  malt: 6,
  dough: 6,
  vanilla: 6,
  caramel: 6,
  molasses: 6,
  butterscotch: 6,
  honey: 6,
  chocolate: 6,
  toffee: 6,
  sugar: 6,
  overallRating: 6,
  value: 6,
};

export const review3: Omit<
  Review,
  "bottleId" | "createdAt" | "updatedAt" | "userId"
> = {
  id: "0ac45694-b00d-4232-a4e9-4382af4829bd",
  imageUrl: "fe8767e3-a311-45a6-a9db-cfe581e7e2b3",

  date: "01/01/2023",
  setting: "Having some bourbon after a day of work",
  glassware: "Copita",
  restTime: "10min",
  nose: "Nutty as all hell, toffee, caramel, cinnamon, burnt sugar, sweet oak, old rickhouse, black pepper, clove, confectioner sugar, grape, plum, almost smells finished.",
  palate:
    "Black peppercorns, cinnamon, caramel, salty tortilla chips, fudge, pecans, confectioners sugar, light clove.",
  finish:
    "Strong, sweet oak, black peppercorn, big caramel notes round the palate. Mint, chocolate, there's a really light fruit note that I can't quite place, but it's well balanced with the darker flavors of the finish.",
  thoughts:
    "Really good stuff. Dark flavors dominate with the caramel, dark chocolate, and peppercorns. There's small waves of a light fruit note I still can't quite place, maybe green grapes? It's really well balanced with the caramel, oak, and chocolate, plus the baking spices and mint make the finish last for a long, long time.",
  cherry: 6,
  strawberry: 6,
  raspberry: 6,
  blackberry: 6,
  blueberry: 6,
  apple: 6,
  banana: 6,
  grape: 6,
  stone: 6,
  citrus: 6,
  tropical: 6,
  pepper: 6,
  bakingSpice: 6,
  cinnamon: 6,
  herbal: 6,
  mint: 6,
  coffee: 6,
  tobacco: 6,
  leather: 6,
  oak: 6,
  toasted: 6,
  smokey: 6,
  peanut: 6,
  almond: 6,
  pecan: 6,
  walnut: 6,
  oily: 6,
  floral: 6,
  corn: 6,
  rye: 6,
  wheat: 6,
  malt: 6,
  dough: 6,
  vanilla: 6,
  caramel: 6,
  molasses: 6,
  butterscotch: 6,
  honey: 6,
  chocolate: 6,
  toffee: 6,
  sugar: 6,
  overallRating: 6,
  value: 6,
};
